apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hurdle-archive-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/nlemberg/hurdle-archive-gitops.git"
    path: "hurdle-archive"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: false
    #   selfHeal: false
