apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nlemberg/hurdle-archive-gitops.git
      targetRevision: HEAD
      ref: app-of-apps
    - repoURL: "https://kubernetes.github.io/ingress-nginx"
      targetRevision: 4.10.0
      chart: ingress-nginx
      helm:
        valueFiles:
          - "$app-of-apps/infra-values/ingress-values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
