apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/nlemberg/hurdle-archive-gitops.git
      targetRevision: HEAD
      ref: app-of-apps
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 57.0.3
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - "$app-of-apps/infra-values/kps-values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # automated:
    #   prune: false
    #   selfHeal: false
