apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  PORT: {{ .Values.app.configmap.PORT | quote }}
  LOG_LEVEL: {{ .Values.app.configmap.LOG_LEVEL | quote }}
  DATABASE_URL: {{ .Values.app.configmap.DATABASE_URL | quote }}
  FLASK_APP: {{ .Values.app.configmap.FLASK_APP | quote }}
  FLASK_DEBUG: {{ .Values.app.configmap.FLASK_DEBUG | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}