apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://{{ .Values.mysql.auth.username }}:pass@mysql-headless/{{ .Values.mysql.auth.database }}
  mysql-root-password: rootpass
  mysql-password: pass
  # mysql-replication-password: pass
