apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.configmap.PORT }}
  selector:
    app: {{ .Release.Name }}